erikfrey/mjx_warp

- mujoco/mjx/_src/smooth.py
- mujoco/mjx/_src/solver.py
- mujoco/mjx/_src/test_util.py
I suggest to just run warmup twice to work around blocksize issues. Of course, a different option is just to upgrade your CUDA version.
> Run warmup twice in testspeed, revert block size changes

- mujoco/mjx/_src/io.py
- mujoco/mjx/_src/solver.py
- mujoco/mjx/_src/solver_test.py
- mujoco/mjx/_src/support.py
- mujoco/mjx/_src/test_util.py
- mujoco/mjx/_src/types.py
the Newton solver is updated to work with a sparse representation of `qM`.
sparse:
```
mjx-testspeed --function=forward --is_sparse=True --mjcf=humanoid/humanoid.xml --batch_size=8192 --nefc_total=32768 --solver=newton --iterations=
1 --ls_iterations=5
```
```
Total JIT time: 108.24 s
Total simulation time: 4.16 s
Total steps per second: 1,970,182
Total realtime factor: 9,850.91 x
Total time per step: 0.51 µs
```
dense:
```
mjx-testspeed --function=forward --is_sparse=False --mjcf=humanoid/humanoid.xml --batch_size=8192 --nefc_total=32768 --solver=newton --iterations=1 --ls_iterations=5
```
```
Total JIT time: 122.94 s
Total simulation time: 4.19 s
Total steps per second: 1,953,057
Total realtime factor: 9,765.28 x …
```
> newton solve sparse qM

- mujoco/mjx/_src/io.py
- mujoco/mjx/_src/test_util.py
- mujoco/mjx/testspeed.py
Assumes that the benchmark model proposes reasonable nefc, ncon given a keyframe.
Changes testspeed flags to take nconmax, njmax.
> Testspeed fixes

- mujoco/mjx/_src/support.py
Result of `mjx-testspeed --function=solve --is_sparse=False --mjcf=humanoid/humanoid.xml --batch_size=8192`
This branch:
```
Total JIT time: 14.99 s
Total simulation time: 1.33 s
Total steps per second: 6,141,383
Total realtime factor: 30,706.92 x
Total time per step: 162.83 ns
```
main:
```
Total JIT time: 0.89 s
Total simulation time: 1.53 s
Total steps per second: 5,363,853
Total realtime factor: 26,819.26 x
Total time per step: 186.43 ns
```
Note that compilation for tiled `mul_m` is quite slow:
```
Module mujoco.mjx._src.support 9a7a6e8 load on device 'cuda:0' took 14520.68 ms  (compiled)
```
Left a TODO - might need some help to debug what's going on there later.
> Tiled mul_m.

- mujoco/mjx/_src/io.py
don't know how I messed that one up. Temp fix to n2 size to hold all the keys, but we should convert to a linear index because we only need the upper or lower triangular part.
> adjust the size of the candidate pair buckets

- mujoco/mjx/_src/forward.py
- mujoco/mjx/_src/forward_test.py
- mujoco/mjx/_src/io.py
- mujoco/mjx/_src/types.py
combining ideas from #32 and #46 to compute `actuator_velocity` with tile operations
```
mjx-testspeed --function=fwd_velocity --is_sparse=False --mjcf=humanoid/humanoid.xml --batch_size=8192
```
this pr (tile operations):
block_dim=32
```
Total JIT time: 0.05 s
Total simulation time: 0.50 s
Total steps per second: 16,324,839
Total realtime factor: 81,624.20 x
Total time per step: 61.26 ns
```
block_dim=64
```
Total JIT time: 0.05 s
Total simulation time: 0.50 s
Total steps per second: 16,337,714
Total realtime factor: 81,688.57 x
Total time per step: 61.21 ns
```
block_dim=128
```
Total JIT time: 0.05 s
Total simulation time: 0.54 s
Total steps per second: 15,142,726
Total realtime …
```
> compute actuator_velocity with tile operations

- mujoco/mjx/_src/solver.py
- mujoco/mjx/_src/solver_test.py
Still a niggling numerical instability but this is mostly working, will fix broken tests tomorrow.
I suspect the things that contributed the most to the speedup are:
- fusing some kernel launches
- using fewer atomic adds
- implemented very simple early exiting
Results of `mjx-testspeed --function=solve --is_sparse=False --mjcf=humanoid/humanoid.xml --batch_size=8192`
This PR:
```
Total JIT time: 0.23 s
Total simulation time: 1.07 s
Total steps per second: 7,659,559
Total realtime factor: 38,297.79 x
Total time per step: 130.56 ns
```
Main:
```
Total JIT time: 0.52 s
Total simulation time: 1.27 s
Total steps per second: 6,431,488
Total realtime factor: 32,157.44 x
Total time per step: 155.49 ns
```
Early exiting seems to be working quite nicely!   🎉 …
> Faster iterative linesearch

- mujoco/mjx/_src/forward.py
tile operations with 1 humanoid:
```
mjx-testspeed --function=fwd_actuation --is_sparse=False --mjcf=humanoid/humanoid.xml --batch_size=8192
```
```
Total JIT time: 0.10 s
Total simulation time: 0.11 s
Total steps per second: 73,175,809
Total realtime factor: 365,879.04 x
Total time per step: 13.67 ns
```
current code with 1 humanoid:
```
mjx-testspeed --function=fwd_actuation --is_sparse=True --mjcf=humanoid/humanoid.xml --batch_size=8192
```
```
Total JIT time: 0.00 s
Total simulation time: 0.06 s
Total steps per second: 133,237,216
Total realtime factor: 666,186.08 x
Total time per step: 7.51 ns
```
tile operations with n_humanoids (n=3):
```
mjx-testspeed --function=fwd_actuation --is_sparse=False …
```
> compute qfrc_actuator with tile operations

- mujoco/mjx/_src/forward.py
Pretty straightforward, similar to implicit integrator. There's more to be gained by fusing in advance as well but I need to figure out interface considerations/composability first.
Timings are pretty similar for a single humanoid, but for 5 humanoids there is a good speedup:
before:
```
Total JIT time: 1.26 s
Total simulation time: 12.44 s
Total steps per second: 658,355
Total realtime factor: 3,291.78 x
Total time per step: 1518.94 ns
```
after:
```
Total JIT time: 1.28 s
Total simulation time: 11.32 s
Total steps per second: 723,993
Total realtime factor: 3,619.96 x
Total time per step: 1381.23 ns
```
> Tiled version of euler integration

- README.md
- mujoco/mjx/_src/collision_driver.py
- mujoco/mjx/_src/constraint.py
- mujoco/mjx/_src/forward.py
- mujoco/mjx/_src/passive.py
- mujoco/mjx/_src/smooth.py
- mujoco/mjx/_src/solver.py
- mujoco/mjx/_src/support.py
- mujoco/mjx/_src/test_util.py
- mujoco/mjx/_src/warp_util.py
- mujoco/mjx/testspeed.py
With this PR we can get some detailed perf numbers of the subcomponents of the physics step.
I've updated the benchmark to compare the results of this to MJX on `humanoid.xml`.
> Trace option for testspeed and some updated benchmarks.

- mujoco/mjx/__init__.py
- mujoco/mjx/_src/broad_phase_test.py
- mujoco/mjx/_src/collision_driver.py
- mujoco/mjx/_src/io.py
- mujoco/mjx/_src/support_test.py
- mujoco/mjx/_src/types.py
- mujoco/mjx/test_data/broadphase.xml
```
mjx-testspeed --function=nxn_broadphase --mjcf=humanoid/humanoid.xml --batch_size=8192
```
```
Total JIT time: 0.01 s
Total simulation time: 0.06 s
Total steps per second: 140,677,877
Total realtime factor: 703,389.38 x
Total time per step: 7.11 ns
```
> n^2 broadphase

- pyproject.toml
MuJoCo 3.3.0 changed its qM layout - we'll fix ours to match after GTC.
> Temporarily pin to MuJoCo==3.2.7

- mujoco/mjx/_src/constraint.py
- mujoco/mjx/_src/constraint_test.py
- mujoco/mjx/_src/io.py
- mujoco/mjx/_src/solver.py
- mujoco/mjx/_src/solver_test.py
- mujoco/mjx/_src/types.py
```
mjx-testspeed --function=solve --mjcf=humanoid/humanoid.xml --batch_size=8192 --solver=newton
```
this pr:
```
Total JIT time: 0.18 s
Total simulation time: 7.96 s
Total steps per second: 1,029,715
Total realtime factor: 5,148.57 x
Total time per step: 971.14 ns
```
main:
```
Total JIT time: 0.18 s
Total simulation time: 8.11 s
Total steps per second: 1,009,871
Total realtime factor: 5,049.36 x
Total time per step: 990.23 ns
```
> restructure solver memory

- mujoco/mjx/_src/forward.py
- mujoco/mjx/_src/io.py
- mujoco/mjx/_src/smooth.py
- mujoco/mjx/_src/support.py
- mujoco/mjx/_src/support_test.py
- mujoco/mjx/_src/types.py
In order to work with JAX graph capture, we must avoid any allocs inside of simulation kernels.
I had to modify `xfrc_accumulate` a bit to remove the mask allocation, but seems to have had no (or perhaps slightly positive) impact on perf.
Result of `mjx-testspeed --function=fwd_acceleration --is_sparse=False --mjcf=humanoid/humanoid.xml --batch_size=8192 --solver=newton --event_trace=True`
This PR:
```
Total JIT time: 0.02 s
Total simulation time: 0.07 s
Total steps per second: 118,669,204
Total realtime factor: 593,346.02 x
Total time per step: 8.43 ns
Event trace:
fwd_acceleration: 6.98
xfrc_accumulate: 2.63
solve_m: 3.49
```
Main:
```
Total JIT time: 0.56 s
Total simulation time: 0.07 s
Total steps per second: …
```
> Remove inline allocs from smooth and xfrc_accumulate.

- mujoco/mjx/_src/forward_test.py
Out of range ctrl creates large qacc which leads to test flakiness.
> Lower ctrl to reasonable in-range domain that produces stable physics.

- mujoco_warp/_src/collision_driver.py
- mujoco_warp/_src/collision_functions.py
- mujoco_warp/_src/io.py
- mujoco_warp/_src/support.py
- mujoco_warp/_src/types.py
modifications to narrowphase to launch one kernel for all collision functions instead of launching one kernel per collision function.
humanoid
```
mjwarp-testspeed --function=collision --mjcf=humanoid/humanoid.xml --batch_size=8192
```
this pr:
```
Total JIT time: 0.02 s
Total simulation time: 0.10 s
Total steps per second: 84,543,850
Total realtime factor: 422,719.25 x
Total time per step: 11.83 ns
```
main:
```
Total JIT time: 0.05 s
Total simulation time: 0.11 s
Total steps per second: 73,888,460
Total realtime factor: 369,442.30 x
Total time per step: 13.53 ns
```
collision.xml
```
mjwarp-testspeed --function=collision --mjcf=collision.xml --batch_size=8192
```
this pr:
```
Total …
```
> modify narrowphase

- mujoco_warp/_src/warp_util.py
This is needed for the JAX<>Warp integration.
> Allow kernel_copy to copy from jax arrays to warp arrays.

- mujoco_warp/_src/solver.py
Prevents crashing when running mjwarp-testspeed with --event_trace=True.
I think this is because of nested traces from solve -> linesarch -> mul_m which the tracer does not handle correctly.
> Remove event_scope from _linesearch.

- mujoco_warp/_src/test_util.py
- mujoco_warp/testspeed.py
Example output with `--measure_alloc=True`:
```
Total JIT time: 0.70 s
Total simulation time: 2.34 s
Total steps per second: 3,499,428
Total realtime factor: 17,497.14 x
Total time per step: 285.76 ns
ncon alloc:
mean     std      min    max  
------------------------------
9469.66  3533.48   3370  19076
11517.8   1136.6   9254  13604
14650.3  1296.75  13021  16324
16305.6  73.2343  16123  16481
16647.1  200.947  16223  17020
16620.7  164.378  16278  17010
16082.2  239.614  15568  16508
15480.4  113.169  15225  15851
15450.9  67.1437  15285  15585
15507.4  76.9735  15365  15780
nefc alloc:
mean     std      min    max  
------------------------------
45211.6  13792.1  17659  78061
61505.3  6728.46  53218  77000
70598.8   4682.4  64598  76554
76262 …
```
> Add support to testspeed to measure ncon, nefc during unroll.

- mujoco_warp/_src/broad_phase_test.py
- mujoco_warp/_src/collision_driver.py
- mujoco_warp/_src/io.py
- mujoco_warp/_src/types.py
Add proper plane support for the sweep and prune broad phase and switch to using bounding spheres similar as the n^2 broad phase does it. Going back to boxes is possible but spheres simplify the handling of plane interactions.
tile_sort support is in the MR too but deactivated since the feature is not yet in warp.
> Add proper plane support for the sweep and prune broad phase
